/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_sfjp_webglmol_NDKmol_NDKmolActivity */

#ifndef _Included_jp_sfjp_webglmol_NDKmol_NDKmolActivity
#define _Included_jp_sfjp_webglmol_NDKmol_NDKmolActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_sfjp_webglmol_NDKmol_NDKmolActivity
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_sfjp_webglmol_NDKmol_NDKmolActivity_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
